### ISSUE TITLE
Multiple versions of CoreFoundation.framework linked

### ISSUE THREAD

**Issue by ambaxter** [PistonDevelopers/rusty-tetris#5]
On OS X I receive the following error:

error: native library `CoreFoundation.framework` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  core-foundation-sys v0.3.0
  core-foundation-sys v0.2.3

**Comment by bvssvni** [comment]
Check the Cargo.lock file to see which packages those versions come from. Try `cargo update` and see if it gets fixed.

**Comment by ambaxter** [comment]
I see the discrepancy:

glutin and winit compete for two different versions of the cocoa library

[[package]]
name = "glutin"
version = "0.7.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "android_glue 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "cgl 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "cocoa 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)",
..,
"winit 0.5.9 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "winit"
version = "0.5.9"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "android_glue 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "cgl 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "cocoa 0.5.2 (registry+https://github.com/rust-lang/crates.io-index)",
..
]

**Comment by ambaxter** [comment]
Looks like I'll need to wait for https://github.com/servo/core-graphics-rs/pull/68

Thanks!
